### ISSUE TITLE
Fallout:Nevada Freezing in vault city on Android Device

### ISSUE THREAD

**Issue by sonilyan** [alexbatalov/fallout2-ce#189] opened 2022-10-24 11:01 UTC
At the beginning of the vault city, after a while, it started to freeze, and finally it stopped moving. Everything is normal on the PC, only the android has found this problem

**Comment by sonilyan** [comment] 2022-10-25 02:14
both armv7a-eabi and arm64 platform has this problem

**Comment by alexbatalov** [comment] 2022-10-25 06:02
Do you have a savegame?

**Comment by sonilyan** [comment] 2022-10-25 07:03
[SLOT05.zip](https://github.com/alexbatalov/fallout2-ce/files/9857860/SLOT05.zip)

**Comment by sonilyan** [comment] 2022-10-25 07:07
on the Android device, at the beginning of the game,  after gathered the party, cannot open the VaultGate : you must wait for you team——but all my team member was around me already

**Comment by alexbatalov** [comment] 2022-10-25 08:54
This particular savegame is screwed, there are 30,000 queued events, each trying to reschedule itself every 5 seconds, no wonder it freezes. I'll try on Android later today to see if it can be reproduced in the new game.

**Comment by sonilyan** [comment] 2022-10-25 09:18
> 

Its seems like that there are some scripts BUG on Android device, I test nevada and vanilla on android and found some BUG:
nevada :
1) cannot open Vault Gate at the start of game
2) freez in vault city

vanilla:
1) Den city, The gang battle does not automatically start the battle——the gang members do not automatically start the battle after running to the church, and the battle needs to be started manually

**Comment by alexbatalov** [comment] 2022-10-26 07:24
I was not able to reproduce (1) and (2) in Nevada on my device. However I had to prepare my distribution (with unpacked master.dat) my lowercasing many proto files and fixing .lst reading (1bbd586cbb8e37a71d658603cd4f0b861c90f25a). For Black Rock and Den please provide save games if possible.

**Comment by sonilyan** [comment] 2022-10-26 08:11
[Den SLOT09.zip](https://github.com/alexbatalov/fallout2-ce/files/9867411/Den.SLOT09.zip)
[BlackRock SLOT01.zip](https://github.com/alexbatalov/fallout2-ce/files/9867413/BlackRock.SLOT01.zip)

talk to the slaves and give them a job,after gaming fading,dude stand in bullpen but slaves not，and Eugene not talk to the dude

**Comment by sonilyan** [comment] 2022-10-26 08:22
(1) and (2) are still reproduce on my  android device，but PC version works fine and use the same data files compare to the android device

**Comment by sonilyan** [comment] 2022-10-26 08:34
I move the Den savegames into PC and it's works fine，but the same game not working on my android device

**Comment by alexbatalov** [comment] 2022-10-27 07:19
What's your device and Android version? I've checked Den save game, combat started as expected.

**Comment by sonilyan** [comment] 2022-10-27 07:38
![1](https://user-images.githubusercontent.com/26177176/198220753-08d5547f-4e37-40d1-a489-de9487092303.jpg)
![2](https://user-images.githubusercontent.com/26177176/198220764-fd4edda5-4d97-4da4-b073-8e6b9257bcfb.jpg)
![3](https://user-images.githubusercontent.com/26177176/198220771-e8da235c-4456-4b1a-9b37-393bf65bb4a4.jpg)

**Comment by APAmk2** [comment] 2023-02-13 17:23
@sonilyan There is some updates happened after that issue, can you close issue if problem was fixed?

**Comment by y0lo** [comment] 2023-05-23 03:40
I can reproduce the issues:
1. Cannot open Vault Gate .
2. At the start of game freez in vault city.

Fallout Nevada FE (2.4.1 FINAL) RUS
Fallout2 CE rel 1.2

**Comment by y0lo** [comment] 2023-05-24 03:40
Details of the second issue:

At the start of game freeze in vault city.
After 10-15 seconds on the second map in Vault City, freezes start at an increasing interval and lead to a rendering stop.

The reason is in increasing amount of events in a queue.
In 10-15 seconds something triggers big amount of events with the same type.

Example of a stuck event data structure:
1. time = {int} 303010
2. type = {int} 3
3. owner = {fallout::Object *} 0xb400007c40f4ff50 
4.  id = {int} 83
5.  tile = {int} 21937
6.  x = {int} 0
7.  y = {int} 0
8.  sx = {int} -317
9.  sy = {int} 358
10.  frame = {int} 0
11.  rotation = {int} 3
12.  fid = {int} 16777285
13.  flags = {int} 536879104
14.  elevation = {int} 0
15.   = {fallout::Object::(anonymous union)} 
16.   field_2C_array = {int [14]} 
17.    [0] = {int} 0
18.    [1] = {int} 0
19.    [2] = {int} 0
20.    [3] = {int} 0
21.    [4] = {int} 0
22.    [5] = {int} 0
23.    [6] = {int} 0
24.    [7] = {int} 8
25.    [8] = {int} 0
26.    [9] = {int} 0
27.    [10] = {int} 33
28.    [11] = {int} 26
29.    [12] = {int} 0
30.    [13] = {int} 0
31.   data = {fallout::ObjectData} 
32.  pid = {int} 16777219
33.  cid = {int} -1
34.  lightDistance = {int} 0
35.  lightIntensity = {int} 0
36.  outline = {int} 0
37.  sid = {int} 67108874
38.  owner = {fallout::Object *} NULL
39.  field_80 = {int} 89

As a workaround if to clear the event queue the issue gone:
https://github.com/alexbatalov/fallout2-ce/blob/main/src/queue.cc#LL380C1-L380C1
`
// cnt is calculated in the loop above 
 if (cnt > 5000) {
        queueClear();
    }`

How to find the root cause of such behavior?

**Comment by y0lo** [comment] 2023-05-24 08:33
Details for the first issue: 
- Cannot open Vault Gate

In the script:
**_scripts/VaCGecko.int_**
```
procedure consolB
begin
   paramParty := 0;
   if ((Pit > 0) and (tile_distance(17896, tile_num(Pit)) <= 7)) then begin
      paramParty := paramParty + 1;
   end
   if ((VaultMan > 0) and (tile_distance(17896, tile_num(VaultMan)) <= 7)) then begin
      paramParty := paramParty + 1;
   end
   if ((DrMoro > 0) and (tile_distance(17896, tile_num(DrMoro)) <= 7)) then begin
      paramParty := paramParty + 1;
   end
```

It looks like **tile_distance()** is not working correctly.

**Comment by y0lo** [comment] 2023-05-24 10:39
The first issue has been found.

https://github.com/alexbatalov/fallout2-ce/blob/53a4437be951f75b10a6d4acb73137868cb59b13/src/interpreter.cc#L1388

Must be unsigned comparison:
` result = (uintptr_t)value[1].pointerValue > (uintptr_t)value[0].integerValue;`

otherwise the (ptr > 0) expression in scripts might not work if ptr value > int positive max.
`if ((Pit > 0) ...`

**Comment by y0lo** [comment] 2023-05-24 13:59
It looks like the second issue with freezing in Vault City is a bug in scripts and not in the engine.
```
procedure timed_event_p_proc
{
  ...
         else {
            if (VCitizenPornoB <= 0) then {
               add_timer_event(self_obj, 20, 1);
            }
            else {
  ...
            }
            add_timer_event(self_obj, 50, 1);
         }
```
If VCitizenPornoB <= 0 then the add_timer_event() called twice and 2 events are added into queue each time.
This overflows the queue.

PS:
There one more issue with comparison of pointer and integers:

https://github.com/alexbatalov/fallout2-ce/blob/53a4437be951f75b10a6d4acb73137868cb59b13/src/interpreter.cc#L1134

It looks like this has been added to support Sonora and Nevada only?
Maybe change this to correctly compare with nullptr? What are default values of init/uninit pointers in the original engine?

**Comment by roginvs** [comment] 2023-05-24 14:40
@y0lo Interesting finding! Just curious: why it works on desktop version of fallout2-ce? What is the difference?

**Comment by y0lo** [comment] 2023-05-24 14:50
@roginvs 
1. I asume the first issue with ponter comparison might work on x86 or sometimes work depends on the pointer value.
2. The issue with the script might work better on PC because the queue is processed faster and freezings are not critical. And depends on the scrpit condition the events can be stopped and the queue will be released in some time.

**Comment by alexbatalov** [comment] 2023-05-24 20:47
Hey there, thanks for your research. I've changed casts to `uintptr_t`, so part (1) is probably fixed. As for the part(2), I don't really think something needs to be done in the engine. This is clearly user-space scripting bug, like endless loop for example.

Can you please if this patch fixes the problem for you. It contains just one script (same for both 2.0.3.3 and 2.4.1).
[patch000.dat.zip](https://github.com/alexbatalov/fallout2-ce/files/11558985/patch000.dat.zip)

**Comment by y0lo** [comment] 2023-05-25 05:33
@alexbatalov thank you. After installing the patch and re-installing apk the issue with freezing in Vault City is resolved.

**Closed** 2023-06-05 13:34 UTC
